project:
  type: website

website:
  title: "Mark Igra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
  page-footer: "© 2012-2024 Mark Igra"

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: source

  

