project:
  type: website

website:
  title: "Mark Igra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

